version: '3'

services:
  main:
    image: main
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./main:/app
    environment:
      - SECRET_KEY=secret
      - DEBUG=True